2019-01-09 16:10:34.2942|ERROR|ViretTool.PresentationLayer.Windows.ViewModels.MainWindowViewModel|Error while submitting framesSystem.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ViretTool.BusinessLayer.Submission.SubmissionService.<SubmitFrameAsync>d__10.MoveNext() in C:\Programming\ViretTool2018\src\ViretTool\ViretTool.BusinessLayer\Submission\SubmissionService.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ViretTool.PresentationLayer.Windows.ViewModels.MainWindowViewModel.<OnSubmittedFramesChanged>d__73.MoveNext() in C:\Programming\ViretTool2018\src\ViretTool\ViretTool.PresentationLayer\Windows\ViewModels\MainWindowViewModel.cs:line 501
